import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { apiGet, apiPost } from '../api/api';
import { PageHeader } from '../components/PageHeader';
import { Button } from '../components/ui/button';
import { Eye, Search, XCircle } from 'lucide-react';
import type { Customer, Order, OrderStatus } from '../types/sales';

const money = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
const labels: Record<OrderStatus, string> = { PENDENTE_PAGAMENTO: 'Pendente', PAGO: 'Pago', CANCELADO: 'Cancelado' };
const colors: Record<OrderStatus, string> = { PENDENTE_PAGAMENTO: 'bg-amber-100 text-amber-800', PAGO: 'bg-emerald-100 text-emerald-800', CANCELADO: 'bg-rose-100 text-rose-800' };

export function Orders() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [status, setStatus] = useState<'ALL' | OrderStatus>('ALL');
  const [customer, setCustomer] = useState('ALL');
  const [start, setStart] = useState('');
  const [end, setEnd] = useState('');
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<Order | null>(null);
  const load = async () => { try { const [data, clientData] = await Promise.all([apiGet<Order[]>('/pedidos'), apiGet<Customer[]>('/clientes')]); setOrders(data); setCustomers(clientData); } catch { toast.error('Nao foi possivel carregar os pedidos.'); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => orders.filter((order) => (status === 'ALL' || order.status === status) && (customer === 'ALL' || order.clienteId === Number(customer)) && (!start || order.dataPedido >= start) && (!end || order.dataPedido <= end) && (!search || `PED-${String(order.id).padStart(3, '0')}`.toLowerCase().includes(search.toLowerCase()) || order.clienteNome.toLowerCase().includes(search.toLowerCase()))), [orders, status, customer, start, end, search]);
  const cancel = async (order: Order) => { try { const updated = await apiPost<Order>(`/pedidos/${order.id}/cancelar`, {}); setOrders((current) => current.map((item) => item.id === updated.id ? updated : item)); setSelected(updated); toast.success('Pedido cancelado.'); } catch { toast.error('Nao foi possivel cancelar o pedido.'); } };
  const count = (value: OrderStatus) => orders.filter((order) => order.status === value).length;
  return <div className="min-h-screen bg-[#f8fafc]"><PageHeader title="🛒 Pedidos" subtitle={`${orders.length} pedidos no total`} actionButton={<Button asChild className="bg-slate-950"><Link to="/vendas">＋ Novo Pedido</Link></Button>} />
    <main className="mx-auto max-w-[1440px] px-5 py-3 sm:px-8"><section className="mb-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{([{ key: 'PENDENTE_PAGAMENTO', label: 'Pendente', style: 'bg-amber-100 text-amber-800' }, { key: 'PAGO', label: 'Pago', style: 'bg-emerald-100 text-emerald-800' }, { key: 'CANCELADO', label: 'Cancelado', style: 'bg-rose-100 text-rose-800' }] as const).map((item) => <div key={item.key} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-3xl font-extrabold">{count(item.key)}</p><span className={`mt-2 inline-block rounded-full px-3 py-1 text-sm font-semibold ${item.style}`}>{item.label}</span></div>)}<div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-3xl font-extrabold">{orders.length}</p><span className="mt-2 inline-block rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-800">Total</span></div></section><section className="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-4"><label className="relative md:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por número ou cliente..." className="h-10 w-full rounded-md bg-slate-100 pl-9 pr-3" /></label><select value={status} onChange={(e) => setStatus(e.target.value as 'ALL' | OrderStatus)} className="h-10 rounded-md border px-3"><option value="ALL">Todos os status</option><option value="PENDENTE_PAGAMENTO">Pendente</option><option value="PAGO">Pago</option><option value="CANCELADO">Cancelado</option></select><select value={customer} onChange={(e) => setCustomer(e.target.value)} className="h-10 rounded-md border px-3"><option value="ALL">Todos os clientes</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.nome}</option>)}</select><input value={start} onChange={(e) => setStart(e.target.value)} type="date" className="h-10 rounded-md border px-3" /><input value={end} onChange={(e) => setEnd(e.target.value)} type="date" className="h-10 rounded-md border px-3" /></section>
      <section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left"><thead className="border-b bg-slate-50 text-sm text-slate-500"><tr><th className="p-5">Pedido</th><th className="p-5">Cliente</th><th className="p-5">Data</th><th className="p-5">Status</th><th className="p-5 text-right">Total</th><th className="p-5 text-right">Ações</th></tr></thead><tbody>{filtered.map((order) => <tr key={order.id} className="border-b last:border-0"><td className="p-5 font-mono font-semibold">PED-{String(order.id).padStart(3, '0')}</td><td className="p-5">{order.clienteNome}</td><td className="p-5 text-slate-500">{new Date(`${order.dataPedido}T12:00:00`).toLocaleDateString('pt-BR')}</td><td className="p-5"><span className={`rounded-full px-3 py-1 text-xs font-bold ${colors[order.status]}`}>{labels[order.status]}</span></td><td className="p-5 text-right font-bold">{money(order.total)}</td><td className="p-5"><div className="flex justify-end gap-2"><Button onClick={() => setSelected(order)} size="icon" variant="ghost" aria-label="Detalhes"><Eye className="h-4 w-4" /></Button>{order.status !== 'CANCELADO' && <Button onClick={() => cancel(order)} size="icon" variant="ghost" className="text-rose-500" aria-label="Cancelar"><XCircle className="h-4 w-4" /></Button>}</div></td></tr>)}{filtered.length === 0 && <tr><td colSpan={6} className="p-8 text-center text-slate-500">Nenhum pedido encontrado.</td></tr>}</tbody></table><p className="border-t p-4 text-right text-slate-500">Total exibido: <strong className="text-slate-950">{money(filtered.filter((o) => o.status !== 'CANCELADO').reduce((sum, o) => sum + o.total, 0))}</strong></p></section>
      {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><section className="max-h-[85vh] w-full max-w-lg overflow-auto rounded-3xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Pedido #{selected.id}</h2><p className="text-slate-600">{selected.clienteNome}</p></div><Button variant="outline" size="sm" onClick={() => setSelected(null)}>Fechar</Button></div><div className="mt-5 space-y-3">{selected.itens.map((item) => <div key={item.id} className="border-b pb-3"><p className="font-medium">{item.produtoNome}</p><p className="text-sm text-slate-500">{item.quantidade} × {money(item.precoUnitario)} = {money(item.subtotal)}</p></div>)}</div><p className="mt-5 text-sm text-slate-600">Desconto aplicado: {money(selected.desconto)}</p><p className="mt-1 text-lg font-bold">Total: {money(selected.total)}</p>{selected.status !== 'CANCELADO' && <Button onClick={() => cancel(selected)} variant="destructive" className="mt-4">Cancelar pedido</Button>}</section></div>}
    </main></div>;
}
