import { Minus, Plus, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { apiGet, apiPost } from '../api/api';
import { PageHeader } from '../components/PageHeader';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import type { Product } from '../types/product';
import type { CartItem, Customer, PaymentMethod } from '../types/sales';

const money = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);

export function Sales() {
  const [products, setProducts] = useState<Product[]>([]); const [customers, setCustomers] = useState<Customer[]>([]);
  const [customerId, setCustomerId] = useState(''); const [cart, setCart] = useState<CartItem[]>([]);
  const [payment, setPayment] = useState<PaymentMethod>('PIX'); const [discount, setDiscount] = useState(0); const [checkout, setCheckout] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([apiGet<Product[]>('/products'), apiGet<Customer[]>('/clientes')]).then(([p, c]) => { setProducts(p); setCustomers(c); }).catch(() => toast.error('Nao foi possivel carregar os dados de venda.')); }, []);
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.precoUnitario * item.quantidade, 0), [cart]); const total = Math.max(0, subtotal - discount);
  const getItem = (id: number | string) => cart.find((item) => String(item.productId) === String(id));
  const update = (id: number | string, quantity: number) => setCart((items) => quantity < 1 ? items.filter((item) => item.productId !== id) : items.map((item) => item.productId === id ? { ...item, quantidade: quantity } : item));
  const add = (product: Product) => setCart((items) => { const item = items.find((entry) => String(entry.productId) === String(product.id)); if (item && item.quantidade >= product.stock) return items; return item ? items.map((entry) => entry === item ? { ...entry, quantidade: entry.quantidade + 1 } : entry) : [...items, { productId: product.id, nome: product.name, precoUnitario: product.price, quantidade: 1 }]; });
  const checkoutStart = () => { if (!customerId || !cart.length) return toast.error('Selecione um cliente e adicione produtos.'); setCheckout(true); };
  const confirm = async () => { setSaving(true); try { const order = await apiPost<{ id: number }>('/pedidos', { clienteId: Number(customerId), itens: cart.map((item) => ({ produtoId: Number(item.productId), quantidade: item.quantidade })), desconto: discount }); await apiPost(`/pedidos/${order.id}/pagamentos`, { formaPagamento: payment }); toast.success('Pagamento confirmado e estoque atualizado.'); setCart([]); setCustomerId(''); setDiscount(0); setCheckout(false); } catch { toast.error('Nao foi possivel confirmar o pagamento.'); } finally { setSaving(false); } };
  return <div className="min-h-screen bg-slate-50"><PageHeader title={checkout ? 'Checkout' : '🛒 Novo Pedido'} subtitle={checkout ? 'Confirme os dados do pagamento' : undefined} actionButton={<div className="flex gap-2"><Button asChild variant="outline"><Link to="/pedidos">Pedidos</Link></Button><Button asChild variant="outline"><Link to="/">Produtos</Link></Button></div>} /><main className="mx-auto grid max-w-7xl gap-8 px-4 py-8 lg:grid-cols-[1fr_400px]">
    {!checkout ? <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="p-6"><label className="font-semibold">Cliente *</label><select className="mt-3 h-11 w-full rounded-xl bg-slate-100 px-4" value={customerId} onChange={(e) => setCustomerId(e.target.value)}><option value="">Selecionar cliente...</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.nome}</option>)}</select></div><div className="border-t p-6 pb-3"><h2 className="text-xl font-bold">Produtos</h2></div>{products.filter((product) => product.stock > 0).map((product) => { const item = getItem(product.id); return <div key={product.id} className="flex items-center justify-between gap-4 border-t px-6 py-4"><div><p className="font-semibold">{product.name}</p><p className="text-sm text-slate-500">{product.category} · Estoque: {product.stock}</p></div><div className="flex items-center gap-4"><strong>{money(product.price)}</strong>{item ? <div className="flex items-center gap-3"><Button size="icon" variant="outline" onClick={() => update(product.id, item.quantidade - 1)} aria-label="Diminuir"><Minus /></Button><span className="w-4 text-center font-semibold">{item.quantidade}</span><Button size="icon" variant="outline" disabled={item.quantidade >= product.stock} onClick={() => add(product)} aria-label="Aumentar"><Plus /></Button></div> : <Button variant="outline" onClick={() => add(product)}><Plus />Adicionar</Button>}</div></div>; })}</section> : <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-5 text-xl font-bold">Forma de pagamento</h2>{(['PIX', 'CARTAO', 'DINHEIRO'] as PaymentMethod[]).map((method) => <label key={method} className={`mb-3 block cursor-pointer rounded-xl border p-4 font-semibold ${payment === method ? 'border-slate-950 bg-slate-50' : ''}`}><input className="mr-3" type="radio" checked={payment === method} onChange={() => setPayment(method)} />{method === 'CARTAO' ? 'Cartão' : method === 'DINHEIRO' ? 'Dinheiro' : 'Pix'}</label>)}<Button variant="outline" onClick={() => setCheckout(false)} className="mt-5">Voltar ao Pedido</Button></section>}
    <aside className="h-fit overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-6"><h2 className="text-xl font-bold">Carrinho <span className="text-base font-normal text-slate-500">({cart.length} {cart.length === 1 ? 'item' : 'itens'})</span></h2></div>{cart.length === 0 ? <p className="p-10 text-center text-slate-500">Nenhum produto adicionado</p> : cart.map((item) => <div key={item.productId} className="flex justify-between gap-3 border-b p-5"><div><p className="font-semibold">{item.nome}</p><p className="text-sm text-slate-500">{item.quantidade} × {money(item.precoUnitario)}</p></div><div className="flex items-center gap-2"><strong>{money(item.precoUnitario * item.quantidade)}</strong>{!checkout && <Button size="icon" variant="ghost" className="text-slate-400 hover:text-rose-600" onClick={() => update(item.productId, 0)} aria-label={`Remover ${item.nome}`}><Trash2 className="h-4 w-4" /></Button>}</div></div>)}<div className="space-y-3 bg-slate-50 p-6"><p>Subtotal <span className="float-right font-semibold">{money(subtotal)}</span></p>{checkout ? <p>Descontos <span className="float-right">- {money(discount)}</span></p> : <label className="block text-sm">Desconto (R$)<Input className="mt-2 bg-white" type="number" min="0" max={subtotal} value={discount} onChange={(e) => setDiscount(Math.min(subtotal, Number(e.target.value)))} /></label>}<div className="border-t pt-3 text-xl font-bold">Total <span className="float-right">{money(total)}</span></div></div><div className="p-6">{checkout ? <Button onClick={confirm} disabled={saving || !cart.length} className="w-full">{saving ? 'Confirmando...' : 'Confirmar Pagamento'}</Button> : <Button onClick={checkoutStart} disabled={!cart.length} className="w-full">Finalizar Checkout</Button>}</div></aside>
  </main></div>;
}
